// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BreadcrumbComponent: typeof import('./views/layout/components/header/components/BreadcrumbComponent.vue')['default']
    ConnfigDrawer: typeof import('./views/layout/components/setting/ConnfigDrawer.vue')['default']
    Dashboard: typeof import('./views/Dashboard.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FooterComponent: typeof import('./views/layout/components/footer/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./views/layout/components/header/HeaderComponent.vue')['default']
    HomeView: typeof import('./views/HomeView.vue')['default']
    LeadView: typeof import('./views/LeadView.vue')['default']
    LeftSidebarComponent: typeof import('./views/layout/components/leftsidebar/LeftSidebarComponent.vue')['default']
    LoginView: typeof import('./views/LoginView.vue')['default']
    MainContent: typeof import('./views/layout/components/MainContent.vue')['default']
    MainLayout: typeof import('./views/layout/MainLayout.vue')['default']
    MemberComponent: typeof import('./views/WeeklyTaskView/components/MemberComponent.vue')['default']
    MenuItem: typeof import('./views/layout/components/leftsidebar/menu/MenuItem.vue')['default']
    PageHeaderComponent: typeof import('./views/layout/components/header/PageHeaderComponent.vue')['default']
    PageSidebarComponent: typeof import('./views/layout/components/pagesidebar/PageSidebarComponent.vue')['default']
    ProjectSelect: typeof import('./views/layout/components/projectpanel/ProjectSelect.vue')['default']
    RightSidebarComponent: typeof import('./components/RightSidebarComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubmenuItem: typeof import('./views/layout/components/leftsidebar/menu/SubmenuItem.vue')['default']
    WeeklyTaskView: typeof import('./views/WeeklyTaskView/WeeklyTaskView.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
